FIND_PATH(ASIO_INCLUDE_DIR asio.hpp 
  ${ASIO_ROOT_DIR}/include
  /usr/include 
  /usr/local/include
)

IF (ASIO_INCLUDE_DIR)
   SET(ASIO_FOUND TRUE)
ENDIF (ASIO_INCLUDE_DIR)

IF (ASIO_FOUND)
   IF (NOT ASIO_FIND_QUIETLY)
      MESSAGE(STATUS "Found ASIO: ${ASIO_INCLUDE_DIR}")
   ENDIF (NOT ASIO_FIND_QUIETLY)
ELSE (ASIO_FOUND)
   IF (ASIO_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Asio")
   ENDIF (ASIO_FIND_REQUIRED)
ENDIF (ASIO_FOUND)